# -*- coding: utf-8 -*-
"""Car24_Price_2Prediction[1].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u8-C5N5k0kI-8MB35Kvqg0iJdmrQH5in

# Aim of the Project

**We aim to analyze the growth and market dominance of major players in the used-car resale market (Cars24, CarWale, Spinny, etc.), using exploratory data analysis and predictive modeling. This analysis will provide insights into revenue trends, market share distribution, customer engagement, and vehicle lifecycle to support potential investors or new entrants assessing market viability.**
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import zscore
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split,RandomizedSearchCV
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from xgboost import XGBRegressor
from datetime import datetime
import joblib
import os

import warnings
warnings.filterwarnings('ignore')

def Cars24_pred():
    try:
        # Load the dataset
        print("Load and undderstand the data")
        df_original = pd.read_csv("cars24_20221210.csv")
        print(df_original.head())

        # Make a copy to preserve original data
        print("\n Original data")
        df = df_original.copy()

        df.head()

        print("\n")
        df.describe()

        print ("We have ",df.shape[0]," number of Rows in our Dataset")
        print ("We have ",df.shape[1]," number of Columns in our Dataset")

        # checking null values
        null_counts = df.isnull().sum()
        null_counts[null_counts > 0]

        # Fill missing 'transmission' and 'bodytype' with mode
        df['transmission'].fillna(df['transmission'].mode()[0], inplace=True)
        df['bodytype'].fillna(df['bodytype'].mode()[0], inplace=True)

        df.duplicated().sum()
        df.drop_duplicates(inplace=True)

        # These may not be useful for ML modeling
        df.drop(['url', 'createdDate', 'storename'], axis=1, inplace=True)

        # Replace negative discounts with 0 (if required)
        df['discountprice'] = df['discountprice'].apply(lambda x: x if x >= 0 else 0)

        # Before removing outliers
        sns.boxplot(x=df['price'])
        plt.title("Before Outlier Removal: Price")
        plt.show()

        def remove_outliers_zscore(df, column, threshold=3):
            df = df.copy()
            df[f'{column}_Zscore'] = np.abs(zscore(df[column]))

            outliers = df[df[f'{column}_Zscore'] > threshold]
            cleaned_df = df[df[f'{column}_Zscore'] <= threshold].drop(columns=[f'{column}_Zscore'])

            print(f"\n- Column: {column}")
            print(f"   - Z-score Threshold: {threshold}")
            print(f"   - Outliers Removed: {outliers.shape[0]}")
            print(f"   - Remaining Rows  : {cleaned_df.shape[0]}")

            return cleaned_df

        df = remove_outliers_zscore(df, 'price')

        # After removing outliers
        sns.boxplot(x=df['price'])
        plt.title("After Outlier Removal: Price")
        plt.show()

        # Plot correlations
        plt.figure(figsize=(10, 6))
        sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
        plt.title("Correlation Heatmap")
        plt.show()


        plt.figure(figsize=(8, 5))
        sns.histplot(df['price'], kde=True)
        plt.title('Distribution of Car Prices')
        plt.xlabel('Price')
        plt.ylabel('Frequency')
        plt.show()

        plt.figure(figsize=(10, 6))
        sns.countplot(y='make', data=df, order=df['make'].value_counts().index)
        plt.title('Car Brand Distribution')
        plt.xlabel('Count')
        plt.ylabel('Brand')
        plt.show()

        sns.displot(df['price'])
        plt.title('Price Distribution')

        log_price = np.log(df['price'])
        df['log_price'] = log_price
        df.head()

        plt.figure(figsize=(16,4))
        plt.subplot(1,2,1)
        sns.scatterplot(data=df,x='price',y='year',palette='rocket')
        plt.title('Price vs Age',size=12,color='black',weight='bold')
        plt.xlabel('Price',size=12,color='black',weight='bold')
        plt.ylabel('Age',size=12,color='black',weight='bold')

        plt.subplot(1,2,2)
        sns.scatterplot(data=df,x='log_price',y='year',palette='rocket')
        plt.title('Log_Price vs Age',size=12,color='black',weight='bold')
        plt.xlabel('Log_Price',size=12,color='black',weight='bold')
        plt.ylabel('Age',size=12,color='black',weight='bold')
        plt.show()

        plt.figure(figsize=(10, 6))
        df.groupby('year')['price'].mean().plot(kind='line', marker='o')
        plt.title('Mean Price Trend by Age')
        plt.xlabel('Age of the Car')
        plt.ylabel('Mean Price')
        plt.grid(True)


        # Get the current date and time
        current_date_time = datetime.now()
        # Extract the year attribute
        current_year = current_date_time.year


        #Feature Engineering
        #Car Age
        df['car_age'] = current_year - df['year']

        #Price per km driven
        df['price_per_km'] = df['price'] / df['kilometerdriven']

        #First owner binary feature
        df['is_1st_owner'] = (df['ownernumber'] == 1).astype(int)

        #Transmission type binary
        df['is_automatic'] = (df['transmission'] == 'Automatic').astype(int)


        #Label encoding for objective column
        encoders_dir = "encoders"
        os.makedirs(encoders_dir, exist_ok=True)

        categorical_cols = ['name', 'make','model', 'city', 'fueltype','transmission','bodytype','registrationcity','registrationstate']

        encoders = {}
        for col in categorical_cols:
            le = LabelEncoder()
            df[col] = le.fit_transform(df[col].astype(str))
            encoders[col] = le
            # Save the classes for app usage
            joblib.dump(le.classes_, os.path.join(encoders_dir, f"{col}_classes.pkl"))

        print(f"Encoders saved to '{encoders_dir}/' directory.")


        X = df[['name', 'make','model', 'city', 'fueltype','transmission','bodytype','registrationcity','registrationstate', 'car_age', 'price_per_km','is_1st_owner', 'is_automatic']]
        y = df['price']

        X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=42)

        # Define models
        #models = {
        #    'Linear Regression': LinearRegression(),
        #    'Random Forest': RandomForestRegressor(random_state=42),
        #    'KNN Regressor': Pipeline([
        #        ('scaler', StandardScaler()),
        #        ('knn', KNeighborsRegressor())
        #    ]),
        #    'XGBoost Regressor': XGBRegressor(random_state=42, verbosity=0)
        #}

        # Store results
        results = {}

        # Train and evaluate models
        #for name, model in models.items():
        #    model.fit(X_train, y_train)
        #    y_pred = model.predict(X_test)

        #    mse = mean_squared_error(y_test, y_pred)
        #    mae = mean_absolute_error(y_test, y_pred)
        #    r2 = r2_score(y_test, y_pred)

        #    results[name] = {
        #        'MSE': mse,
        #        'MAE': mae,
        #        'R2 Score': r2
        #    }
        print("\nXGBoost Regression result before Hypertune")
        model = XGBRegressor(random_state=42)

        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        mse = mean_squared_error(y_test, y_pred)
        mae = mean_absolute_error(y_test, y_pred)
        r2 = r2_score(y_test, y_pred)

        results['XGBoost Regression'] = {
                'MSE': mse,
                'MAE': mae,
                'R2 Score': r2
            }

        # Print results
        for model_name, scores in results.items():
            print(f"{model_name}:\n"
                  f"\tMSE: {scores['MSE']:.2f}\n"
                  f"\tMAE: {scores['MAE']:.2f}\n"
                  f"\tR2 Score: {scores['R2 Score']:.4f}\n")


        params = {
            'n_estimators':[100,200,300,500],
            'max_depth':[3,5,7,10],
            'learning_rate':[0.01,0.05,0.1,0.3],
            'subsample':[0.6,0.8,1.0],
            'colsample_bytree':[0.6,0.8,1.0],
            'gamma':[0,0.1,0.2,0.3]
        }

        random_search = RandomizedSearchCV(
            estimator = model,
            param_distributions= params,
            n_iter=20,
            scoring='neg_mean_squared_error',
            cv=3,
            verbose=2,
            random_state=42,
            n_jobs=-1
        )

        random_search.fit(X_train,y_train)
        print("\nXGBoost Regression result after Hypertune")
        print("\nBest Parameters:",random_search.best_params_)

        best_xgb = random_search.best_estimator_
        best_xgb.fit(X_train,y_train)

        y_pred = best_xgb.predict(X_test)

        print("\nFinal MSE:",mean_squared_error(y_test,y_pred))
        print("Final MAE:",mean_absolute_error(y_test,y_pred))
        print("Final R2:",r2_score(y_test,y_pred))

        joblib.dump(best_xgb,"Car_Price_Prediction.pkl")


    except FileNotFoundError:
        print("Error")

Cars24_pred()

